# Generated by Django 3.1.6 on 2021-02-14 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210212_0515'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='followers',
            field=models.ManyToManyField(blank=True, null=True, related_name='_profile_followers_+', to='users.Profile'),
        ),
        migrations.AddField(
            model_name='profile',
            name='followers_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='following',
            field=models.ManyToManyField(blank=True, null=True, related_name='_profile_following_+', to='users.Profile'),
        ),
        migrations.AddField(
            model_name='profile',
            name='following_total',
            field=models.IntegerField(default=0),
        ),
    ]
