# Generated by Django 3.1.6 on 2021-02-08 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0002_auto_20210207_1813'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tweet',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='tweet',
            old_name='date_joined',
            new_name='created_at',
        ),
    ]
